# Generated by Django 4.1.2 on 2023-06-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_stock_alert',
            field=models.IntegerField(default=1),
        ),
    ]
