# Generated by Django 4.1.2 on 2023-06-25 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='item_cost',
            new_name='item_selling_price',
        ),
    ]
