# Generated by Django 4.1.2 on 2023-06-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='received_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=100)),
                ('item_selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('txn_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_type', models.CharField(max_length=10)),
            ],
        ),
    ]
