# Generated by Django 4.1.2 on 2023-07-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_received_order_item_stock_alert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='received_order',
            old_name='item_quantity',
            new_name='item_quantity_orered',
        ),
        migrations.RenameField(
            model_name='received_order',
            old_name='type',
            new_name='order_type',
        ),
        migrations.RemoveField(
            model_name='received_order',
            name='item_stock_alert',
        ),
    ]
