# Generated by Django 4.1.2 on 2023-07-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_item_quantity_received_order_item_quantity_orered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='received_order',
            old_name='item_quantity_orered',
            new_name='item_quantity',
        ),
    ]
