# Generated by Django 4.1.2 on 2023-07-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_item_quantity_orered_received_order_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='received_order',
            name='item_selling_price',
        ),
    ]
