# Generated by Django 4.1.2 on 2023-07-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_received_order_item_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='received_order',
            name='item_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
